### ISSUE TITLE
Consider allowing ++ inside loops

### ISSUE THREAD

**Issue by giodamelio** [scottnonnenberg/eslint-config-thehelp#3]
I like the [`no-plusplus`](http://eslint.org/docs/rules/no-plusplus) rule, but it is a bit annoying not being able to use it in for loops. The whole reason the rule exists isn't really valid in that case anyways. There is already [an option](http://eslint.org/docs/rules/no-plusplus#allowforloopafterthoughts) to allow `++` only in the last part of loops.

**Comment by scottnonnenberg** [comment]
Honestly, I've been fine using `+= 1` in my `for` loops. But I also didn't know about the `allowForLoopAfterthoughts` option - I think I'd be cool turning that on in this config. Maybe you'd like to assemble a pull request for that?

**Comment by giodamelio** [comment]
Sure.
